In [1]:
import torch
import torch.nn as NN

In [21]:
X = torch.Tensor([
    [0., 0., 0.], 
    [0., 0., 1.],
    [0., 1., 0.],
    [0., 1., 1.],
    [1., 0., 0.],
    [1., 0., 1.],
    [1., 1., 0.],
    [1., 1., 1.]
])

A = torch.Tensor([1., 0., 0.])
B = torch.Tensor([0., 1., 0.])
C = torch.Tensor([0., 0., 1.])

AB = A + B
AC = A + C
BC = B + C
ABC = A + B + C

# 6A    4B     3C
y = torch.Tensor([
    [1., 0., 0.], # A
    [0., 1., 0.], # B
    [0., 0., 1.], # C
    [1., 1., 0.], # AB
    [1., 0., 1.], # AC
    [1., 1., 0.], # AB
    [1., 1., 1.], # ABC
    [1., 0., 0.]  # A
])

e = 1e-7

In [25]:
X.shape

torch.Size([8, 3])

In [28]:
preloss_pos = y * torch.log(X+e)
preloss_neg = (1 - y) * torch.log(X+e)

In [34]:
for el in preloss_pos.sum(axis=1):
    print(el)

tensor(-16.1181)
tensor(-16.1181)
tensor(-16.1181)
tensor(-16.1181)
tensor(-16.1181)
tensor(-16.1181)
tensor(-16.1181)
tensor(1.1921e-07)


In [35]:
for el in preloss_neg.sum(axis=1):
    print(el)

tensor(-32.2362)
tensor(-16.1181)
tensor(-16.1181)
tensor(1.1921e-07)
tensor(-16.1181)
tensor(1.1921e-07)
tensor(0.)
tensor(2.3842e-07)


In [31]:
preloss = preloss_pos + preloss_neg

In [36]:
for el in preloss.sum(axis=1):
    print(el)

tensor(-48.3543)
tensor(-32.2362)
tensor(-32.2362)
tensor(-16.1181)
tensor(-32.2362)
tensor(-16.1181)
tensor(-16.1181)
tensor(3.5763e-07)


In [38]:
preloss.mean()

tensor(-8.0590)

In [2]:
X = torch.Tensor([0., 1., 1., 0., 1.])
X2 = torch.Tensor([0.7971, 0.0775, 0.9842, 0.4109, 0.6770])
y = torch.Tensor([0., 0., 0., 1., 1.])
one = torch.ones(1)
zero = torch.zeros(1)

In [3]:
mse = lambda X, y: ((X-y)**2).mean()
rmse = lambda X, y: torch.sqrt(mse(X, y))

In [4]:
def kld(X, y, e=1e-7):
    probs = (X+e) * torch.log((X+e) / (y+e))
    return probs.mean()

In [5]:
def kld_max(X, y, eps=1e-7):
    probs_1 = kld(X, y)
    probs_2 = kld(y, X)
    return probs_1 + probs_2

In [6]:
def cel(X, y, e=1e-7):
    t1 = y * torch.log(X+e)
    t2 = (1 - y) * torch.log(X+e)
    return -(t1 + t2).mean()

In [15]:
class CustomLoss:
    def __init__(self):
        self.kl = NN.KLDivLoss()
        self.cel = NN.BCELoss()
    def __call__(self, X, y):
        com_loss = self.kl(X, y) + self.cel(X, y)
        return torch.pow(com_loss, 2.)

In [16]:
cust = CustomLoss()
cust(X, y)

tensor(3576.0398)

In [9]:
NN.KLDivLoss()(X, y)

tensor(-0.2000)

In [10]:
print("MSE:", mse(X, y))
print("RMSE:",rmse(X, y))
print("CEL:",cel(X, y))
print("KLDXY:",kld(X, y))
print("KLDYX:",kld(y, X))
print("KLDMAX:",kld_max(X, y))

MSE: tensor(0.6000)
RMSE: tensor(0.7746)
CEL: tensor(6.4472)
KLDXY: tensor(6.4472)
KLDYX: tensor(3.2236)
KLDMAX: tensor(9.6709)


In [9]:
X3 = torch.Tensor([1, 1, 1, 1])
y3 = torch.Tensor([0, 0, 0, 1])
kld(X3, y3)

tensor(12.0886)

In [11]:
X3 = torch.Tensor([0, 0, 0, 1])
y3 = torch.Tensor([1, 1, 1, 1])
kld(X3, y3)

tensor(-1.2089e-06)

In [12]:
combs = [(zero, zero), (one, zero), (zero, one), (one, one)]

In [13]:
for comb in combs:
    print(comb, kld(comb[0], comb[1]))

(tensor([0.]), tensor([0.])) tensor(0.)
(tensor([1.]), tensor([0.])) tensor(16.1181)
(tensor([0.]), tensor([1.])) tensor(-1.6118e-06)
(tensor([1.]), tensor([1.])) tensor(0.)


In [13]:
X2 = torch.rand(5)
#y2 = (torch.rand(5) > 0.5).float()

In [14]:
kld(X2, y2)

NameError: name 'y2' is not defined

In [ ]:
X2