In [1]:
from exp.utils import *
from exp.models import *
from exp.losses import *
from tqdm.notebook import tqdm
from multiprocessing import Pool

import torch
import torch.nn as NN
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets, transforms

In [2]:
picked_labels = ["Atelectasis", "Cardiomegaly", "Pneumonia"]
already_pretrained_labels = []#["Atelectasis"]#["Cardiomegaly", "Pneumonia"]
already_pretrained_lrs = []#[1e-8]#[1e-10, 1e-10]
already_pretrained = {k:v for k,v in zip(already_pretrained_labels, already_pretrained_lrs)}
already_trained = []#["Atelectasis"]
train_labels = [l for l in picked_labels if l not in already_trained]

In [3]:
architecure = "MNASNET1_v2"

In [4]:
for label in sorted(train_labels):
    print(f"Training model to classify '{label}'")
    
    # Seed
    seed = 92
    seed_everything(seed)
    
    # Inital setup
    model_name = f"{architecure}_{label}"#f"sam_densenet_v1_{label}"
    #model_type = "densenet"
    bs = 16
    lr = 1e-3
    epochs = 50
    patience = 1
    rho = 0.05
    with_reset = True
    image_size = (224, 224)
    device = get_device()
    labels = get_labels()
    
    # Load data
    train_df, valid_df, test_df = get_dataframes(include_labels=labels, 
                                                 small=False)
    print(train_df.shape, valid_df.shape, test_df.shape)
    train_df = get_binary_df(label, train_df)
    valid_df = get_binary_df(label, valid_df)
    test_df  = get_binary_df(label, test_df)
    
    # Compute label weights
    train_label = train_df[[label]].values
    neg_weights, pos_weights = compute_class_freqs(train_label)
    neg_weights, pos_weights = torch.Tensor(neg_weights), torch.Tensor(pos_weights)
    print(neg_weights, pos_weights)
    
    # Get transforms
    train_tfs, test_tfs = get_transforms(image_size=image_size)
    
    # Create datasets
    train_ds = CRX8_Data(train_df, get_image_path(), label, image_size=image_size, transforms=train_tfs)
    valid_ds = CRX8_Data(valid_df, get_image_path(), label, image_size=image_size, transforms=test_tfs)
    test_ds  = CRX8_Data(test_df , get_image_path(), label, image_size=image_size, transforms=test_tfs)
    
    # Create dataloaders
    train_dl = DataLoader(train_ds, batch_size=bs, shuffle=True)
    valid_dl = DataLoader(valid_ds, batch_size=bs, shuffle=False)
    test_dl  = DataLoader(test_ds,  batch_size=bs, shuffle=False)
    dataloaders = {
        "train": train_dl,
        "val": valid_dl,
        "test": test_dl
    }
    
    # Load imagenet-pretrained model
    if label in list(already_pretrained.keys()):
        model = load_model(model_name)
        lr = already_pretrained[label]
        print("Loaded pretrained model!")
    else:
        model = pretrained_mnasnet1_0()
    model = model.to(device)
    
    
    
    # Get criterion and optimizer
    criterion = get_weighted_loss_with_logits(pos_weights.to(device), 
                                              neg_weights.to(device))
    sam_optimizer = SAM(model.parameters(), torch.optim.Adam, lr=lr, rho=rho)
    
    # Train model
    model, history = fit(model, criterion, sam_optimizer, 
                         dataloaders, model_name, epochs, 
                         lr, sam=True, with_reset=with_reset, metric="loss", patience=patience)

FERTIG()

Training model to classify 'Atelectasis'
Using the GPU!
(69219, 25) (17305, 25) (25596, 24)
tensor([0.0961]) tensor([0.9039])
Epoch 1:



Train: Loss: 0.103, Acc: 0.650, AUROC: 0.754



Val: Loss: 0.260, Acc: 0.700, AUROC: 0.765
Saved model with loss 0.2599
Epoch 2:



Train: Loss: 0.097, Acc: 0.674, AUROC: 0.785



Val: Loss: 0.180, Acc: 0.673, AUROC: 0.781
Saved model with loss 0.1796
Epoch 3:



Train: Loss: 0.094, Acc: 0.691, AUROC: 0.801



Val: Loss: 0.121, Acc: 0.691, AUROC: 0.799
Saved model with loss 0.1213
Epoch 4:



Train: Loss: 0.092, Acc: 0.702, AUROC: 0.813



Val: Loss: 0.104, Acc: 0.670, AUROC: 0.799
Saved model with loss 0.1036
Epoch 5:



Train: Loss: 0.091, Acc: 0.709, AUROC: 0.818



Val: Loss: 0.105, Acc: 0.732, AUROC: 0.806
Resetted model to previous best.
Lowered lr to 0.0001
Epoch 6:



Train: Loss: 0.091, Acc: 0.693, AUROC: 0.824



Val: Loss: 0.094, Acc: 0.720, AUROC: 0.803
Saved model with loss 0.0938
Epoch 7:



Train: Loss: 0.092, Acc: 0.692, AUROC: 0.823



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Saved model with loss 0.0937
Epoch 8:



Train: Loss: 0.091, Acc: 0.693, AUROC: 0.823



Val: Loss: 0.094, Acc: 0.712, AUROC: 0.803
Saved model with loss 0.0937
Epoch 9:



Train: Loss: 0.091, Acc: 0.691, AUROC: 0.823



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Saved model with loss 0.0937
Epoch 10:



Train: Loss: 0.091, Acc: 0.693, AUROC: 0.825



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Resetted model to previous best.
Lowered lr to 1e-05
Epoch 11:



Train: Loss: 0.091, Acc: 0.693, AUROC: 0.824



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-06
Epoch 12:



Train: Loss: 0.091, Acc: 0.693, AUROC: 0.824



Val: Loss: 0.094, Acc: 0.712, AUROC: 0.803
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-07
Epoch 13:



Train: Loss: 0.091, Acc: 0.693, AUROC: 0.824



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Saved model with loss 0.0937
Epoch 14:



Train: Loss: 0.091, Acc: 0.693, AUROC: 0.825



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Saved model with loss 0.0937
Epoch 15:



Train: Loss: 0.092, Acc: 0.693, AUROC: 0.824



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-08
Epoch 16:



Train: Loss: 0.091, Acc: 0.694, AUROC: 0.825



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Resetted model to previous best.
Lowered lr to 1.0000000000000003e-09
Epoch 17:



Train: Loss: 0.092, Acc: 0.692, AUROC: 0.824



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Resetted model to previous best.
Lowered lr to 1.0000000000000003e-10
Epoch 18:



Train: Loss: 0.091, Acc: 0.692, AUROC: 0.824



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Resetted model to previous best.
Lowered lr to 1.0000000000000003e-11
Epoch 19:



Train: Loss: 0.091, Acc: 0.693, AUROC: 0.825



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-12
Epoch 20:



Train: Loss: 0.091, Acc: 0.692, AUROC: 0.825



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Saved model with loss 0.0936
Epoch 21:



Train: Loss: 0.091, Acc: 0.693, AUROC: 0.825



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-13
Epoch 22:



Train: Loss: 0.092, Acc: 0.692, AUROC: 0.825



Val: Loss: 0.094, Acc: 0.713, AUROC: 0.803
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-14
Learning rate is basically zero. Stopping training.
Training model to classify 'Cardiomegaly'
Using the GPU!
(69219, 25) (17305, 25) (25596, 24)
tensor([0.0203]) tensor([0.9797])
Epoch 1:



Train: Loss: 0.023, Acc: 0.642, AUROC: 0.775



Val: Loss: 0.288, Acc: 0.983, AUROC: 0.648
Saved model with loss 0.2879
Epoch 2:



Train: Loss: 0.019, Acc: 0.741, AUROC: 0.850



Val: Loss: 0.134, Acc: 0.723, AUROC: 0.852
Saved model with loss 0.1344
Epoch 3:



Train: Loss: 0.019, Acc: 0.728, AUROC: 0.858



Val: Loss: 0.103, Acc: 0.812, AUROC: 0.903
Saved model with loss 0.1029
Epoch 4:



Train: Loss: 0.017, Acc: 0.757, AUROC: 0.882



Val: Loss: 0.032, Acc: 0.819, AUROC: 0.918
Saved model with loss 0.0320
Epoch 5:



Train: Loss: 0.017, Acc: 0.763, AUROC: 0.888



Val: Loss: 0.023, Acc: 0.831, AUROC: 0.902
Saved model with loss 0.0227
Epoch 6:



Train: Loss: 0.016, Acc: 0.766, AUROC: 0.896



Val: Loss: 0.025, Acc: 0.835, AUROC: 0.911
Resetted model to previous best.
Lowered lr to 0.0001
Epoch 7:



Train: Loss: 0.015, Acc: 0.853, AUROC: 0.909



Val: Loss: 0.014, Acc: 0.830, AUROC: 0.914
Saved model with loss 0.0141
Epoch 8:



Train: Loss: 0.015, Acc: 0.854, AUROC: 0.910



Val: Loss: 0.014, Acc: 0.834, AUROC: 0.915
Saved model with loss 0.0139
Epoch 9:



Train: Loss: 0.015, Acc: 0.853, AUROC: 0.914



Val: Loss: 0.014, Acc: 0.860, AUROC: 0.915
Saved model with loss 0.0139
Epoch 10:



Train: Loss: 0.015, Acc: 0.853, AUROC: 0.910



Val: Loss: 0.014, Acc: 0.860, AUROC: 0.915
Saved model with loss 0.0139
Epoch 11:



Train: Loss: 0.015, Acc: 0.853, AUROC: 0.910



Val: Loss: 0.014, Acc: 0.861, AUROC: 0.915
Saved model with loss 0.0139
Epoch 12:



Train: Loss: 0.016, Acc: 0.853, AUROC: 0.907



Val: Loss: 0.014, Acc: 0.860, AUROC: 0.915
Resetted model to previous best.
Lowered lr to 1e-05
Epoch 13:



Train: Loss: 0.015, Acc: 0.853, AUROC: 0.911



Val: Loss: 0.014, Acc: 0.834, AUROC: 0.915
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-06
Epoch 14:



Train: Loss: 0.015, Acc: 0.853, AUROC: 0.910



Val: Loss: 0.014, Acc: 0.861, AUROC: 0.915
Saved model with loss 0.0139
Epoch 15:



Train: Loss: 0.015, Acc: 0.852, AUROC: 0.910



Val: Loss: 0.014, Acc: 0.861, AUROC: 0.915
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-07
Epoch 16:



Train: Loss: 0.015, Acc: 0.853, AUROC: 0.909



Val: Loss: 0.014, Acc: 0.860, AUROC: 0.915
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-08
Epoch 17:



Train: Loss: 0.015, Acc: 0.853, AUROC: 0.911



Val: Loss: 0.014, Acc: 0.834, AUROC: 0.915
Resetted model to previous best.
Lowered lr to 1.0000000000000003e-09
Epoch 18:



Train: Loss: 0.015, Acc: 0.853, AUROC: 0.908



Val: Loss: 0.014, Acc: 0.861, AUROC: 0.915
Resetted model to previous best.
Lowered lr to 1.0000000000000003e-10
Epoch 19:



Train: Loss: 0.015, Acc: 0.853, AUROC: 0.909



Val: Loss: 0.014, Acc: 0.860, AUROC: 0.915
Resetted model to previous best.
Lowered lr to 1.0000000000000003e-11
Epoch 20:



Train: Loss: 0.015, Acc: 0.853, AUROC: 0.910



Val: Loss: 0.014, Acc: 0.834, AUROC: 0.915
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-12
Epoch 21:



Train: Loss: 0.015, Acc: 0.852, AUROC: 0.910



Val: Loss: 0.014, Acc: 0.860, AUROC: 0.915
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-13
Epoch 22:



Train: Loss: 0.015, Acc: 0.853, AUROC: 0.909



Val: Loss: 0.014, Acc: 0.860, AUROC: 0.915
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-14
Learning rate is basically zero. Stopping training.
Training model to classify 'Pneumonia'
Using the GPU!
(69219, 25) (17305, 25) (25596, 24)
tensor([0.0097]) tensor([0.9903])
Epoch 1:



Train: Loss: 0.013, Acc: 0.596, AUROC: 0.547



Val: Loss: 0.016, Acc: 0.625, AUROC: 0.605
Saved model with loss 0.0159
Epoch 2:



Train: Loss: 0.013, Acc: 0.414, AUROC: 0.578



Val: Loss: 0.061, Acc: 0.297, AUROC: 0.516
Resetted model to previous best.
Lowered lr to 0.0001
Epoch 3:



Train: Loss: 0.013, Acc: 0.461, AUROC: 0.601



Val: Loss: 0.014, Acc: 0.572, AUROC: 0.625
Saved model with loss 0.0144
Epoch 4:



Train: Loss: 0.013, Acc: 0.460, AUROC: 0.611



Val: Loss: 0.014, Acc: 0.580, AUROC: 0.626
Resetted model to previous best.
Lowered lr to 1e-05
Epoch 5:



Train: Loss: 0.013, Acc: 0.461, AUROC: 0.606



Val: Loss: 0.014, Acc: 0.591, AUROC: 0.626
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-06
Epoch 6:



Train: Loss: 0.013, Acc: 0.460, AUROC: 0.604



Val: Loss: 0.014, Acc: 0.581, AUROC: 0.626
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-07
Epoch 7:



Train: Loss: 0.013, Acc: 0.462, AUROC: 0.597



Val: Loss: 0.014, Acc: 0.587, AUROC: 0.626
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-08
Epoch 8:



Train: Loss: 0.013, Acc: 0.460, AUROC: 0.604



Val: Loss: 0.014, Acc: 0.580, AUROC: 0.626
Resetted model to previous best.
Lowered lr to 1.0000000000000003e-09
Epoch 9:



Train: Loss: 0.013, Acc: 0.461, AUROC: 0.595



Val: Loss: 0.014, Acc: 0.590, AUROC: 0.626
Resetted model to previous best.
Lowered lr to 1.0000000000000003e-10
Epoch 10:



Train: Loss: 0.013, Acc: 0.461, AUROC: 0.604



Val: Loss: 0.014, Acc: 0.587, AUROC: 0.626
Resetted model to previous best.
Lowered lr to 1.0000000000000003e-11
Epoch 11:



Train: Loss: 0.013, Acc: 0.462, AUROC: 0.612



Val: Loss: 0.014, Acc: 0.587, AUROC: 0.626
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-12
Epoch 12:



Train: Loss: 0.013, Acc: 0.459, AUROC: 0.600



Val: Loss: 0.014, Acc: 0.581, AUROC: 0.626
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-13
Epoch 13:



Train: Loss: 0.013, Acc: 0.462, AUROC: 0.605



Val: Loss: 0.014, Acc: 0.590, AUROC: 0.626
Resetted model to previous best.
Lowered lr to 1.0000000000000002e-14
Learning rate is basically zero. Stopping training.
FERTIG! :D
